# -*- coding: utf-8 -*-
"""Student_Goal_Tracking_System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17LpGBw3s_ECYqZSSiOFOCA0Dbr77mwWR
"""

print("========================================")
print("      STUDENT GOAL TRACKING SYSTEM")
print("========================================")
print("Project started successfully!")

import sqlite3

print("SQLite imported successfully!")

import sqlite3

conn = sqlite3.connect("student_goals.db")
cursor = conn.cursor()

print("Database connected successfully!")

cursor.execute("""
CREATE TABLE IF NOT EXISTS students (
    student_id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
)
""")

conn.commit()

print("Students table created successfully!")

cursor.execute("""
CREATE TABLE IF NOT EXISTS goals (
    goal_id INTEGER PRIMARY KEY AUTOINCREMENT,
    student_id INTEGER,
    goal_name TEXT NOT NULL,
    category TEXT,
    description TEXT,
    target_date TEXT,
    progress INTEGER DEFAULT 0,
    status TEXT DEFAULT 'Pending',
    FOREIGN KEY (student_id) REFERENCES students(student_id)
)
""")

conn.commit()

print("Goals table created successfully!")

cursor.execute("""
SELECT name
FROM sqlite_master
WHERE type='table'
""")

tables = cursor.fetchall()

print("Tables in database:")

for table in tables:
    print(table[0])

def register_student():
    print("\n========== STUDENT REGISTRATION ==========")

    name = input("Enter student name: ")
    email = input("Enter email: ")
    password = input("Enter password: ")

    try:
        cursor.execute("""
        INSERT INTO students (name, email, password)
        VALUES (?, ?, ?)
        """, (name, email, password))

        conn.commit()

        print("\nRegistration successful!")

    except sqlite3.IntegrityError:
        print("\nEmail already registered!")

register_student()

cursor.execute("SELECT * FROM students")

students = cursor.fetchall()

print("========== REGISTERED STUDENTS ==========")

for student in students:
    print(student)

def login_student():

    print("\n========== STUDENT LOGIN ==========")

    email = input("Enter email: ")
    password = input("Enter password: ")

    cursor.execute("""
    SELECT student_id, name
    FROM students
    WHERE email = ? AND password = ?
    """, (email, password))

    student = cursor.fetchone()

    if student:
        print("\nLogin successful!")
        print("Welcome,", student[1])

        return student[0]

    else:
        print("\nInvalid email or password!")

        return None

student_id = login_student()

def add_goal(student_id):

    print("\n========== ADD GOAL ==========")

    goal_name = input("Enter goal name: ")
    category = input("Enter category: ")
    description = input("Enter description: ")
    target_date = input("Enter target date (DD-MM-YYYY): ")

    cursor.execute("""
    INSERT INTO goals
    (student_id, goal_name, category, description, target_date)
    VALUES (?, ?, ?, ?, ?)
    """,
    (student_id, goal_name, category, description, target_date))

    conn.commit()

    print("\nGoal added successfully!")

add_goal(student_id)

add_goal(student_id)

add_goal(student_id)

def view_goals(student_id):

    cursor.execute("""
    SELECT goal_id, goal_name, category,
           description, target_date,
           progress, status
    FROM goals
    WHERE student_id = ?
    """, (student_id,))

    goals = cursor.fetchall()

    print("\n==============================================")
    print("              MY GOALS")
    print("==============================================")

    if not goals:
        print("No goals found.")

    else:
        for goal in goals:

            print("\nGoal ID     :", goal[0])
            print("Goal Name   :", goal[1])
            print("Category    :", goal[2])
            print("Description :", goal[3])
            print("Target Date :", goal[4])
            print("Progress    :", str(goal[5]) + "%")
            print("Status      :", goal[6])
            print("----------------------------------------------")

view_goals(student_id)

def update_progress(student_id):

    print("\n========== UPDATE PROGRESS ==========")

    goal_id = int(input("Enter goal ID: "))
    progress = int(input("Enter progress (0-100): "))

    if progress < 0 or progress > 100:
        print("Progress must be between 0 and 100.")
        return

    if progress == 100:
        status = "Completed"
    else:
        status = "Pending"

    cursor.execute("""
    UPDATE goals
    SET progress = ?, status = ?
    WHERE goal_id = ? AND student_id = ?
    """,
    (progress, status, goal_id, student_id))

    conn.commit()

    if cursor.rowcount > 0:
        print("\nProgress updated successfully!")

    else:
        print("\nGoal not found.")

update_progress(student_id)

view_goals(student_id)

update_progress(student_id)

view_goals(student_id)

def dashboard(student_id):

    cursor.execute("""
    SELECT
        COUNT(*) AS total_goals,
        SUM(CASE WHEN status = 'Completed' THEN 1 ELSE 0 END),
        SUM(CASE WHEN status = 'Pending' THEN 1 ELSE 0 END),
        COALESCE(AVG(progress), 0)
    FROM goals
    WHERE student_id = ?
    """, (student_id,))

    result = cursor.fetchone()

    total_goals = result[0]
    completed_goals = result[1] or 0
    pending_goals = result[2] or 0
    average_progress = result[3]

    print("\n====================================")
    print("       STUDENT GOAL DASHBOARD")
    print("====================================")

    print("Total Goals       :", total_goals)
    print("Completed Goals   :", completed_goals)
    print("Pending Goals     :", pending_goals)
    print("Average Progress  :", round(average_progress), "%")

    print("====================================")

dashboard(student_id)

def student_menu(student_id):

    while True:

        print("\n====================================")
        print("       STUDENT GOAL TRACKING")
        print("====================================")

        print("1. Add Goal")
        print("2. View Goals")
        print("3. Update Progress")
        print("4. Dashboard")
        print("5. Delete Goal")
        print("6. Logout")
        print("7. Exit")

        choice = input("Enter your choice: ")

        if choice == "1":
            add_goal(student_id)

        elif choice == "2":
            view_goals(student_id)

        elif choice == "3":
            update_progress(student_id)

        elif choice == "4":
            dashboard(student_id)

        elif choice == "5":
            print("\nLogged out successfully!")
            break

        elif choice == "6":
            print("\nThank you for using Student Goal Tracking System!")
            print("Program exited successfully.")
            return

        else:
            print("\nInvalid choice! Please enter 1-7.")

student_menu(student_id)